# Generated by Django 4.2.5 on 2023-09-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sturesponse',
            old_name='responcetype',
            new_name='responsetype',
        ),
    ]
