# Generated by Django 4.2.4 on 2023-09-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='enquirytext',
            field=models.TextField(null=True),
        ),
    ]
