# Generated by Django 4.2.4 on 2023-09-08 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0003_rename_contact_enquiry_contactno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='regdaate',
            new_name='regdate',
        ),
    ]
